spring:
  application:
    name: cloud-test
  cloud:
    config:
      uri: http://localhost:8888
      label: master
      enabled: true
  #      profile: ${spring.profiles.active}, host, db # default {spring.profiles.active}
  config:
    import: 'optional:configserver:'
  profiles:
    active: dev, venom